### ISSUE TITLE
jinja2.exceptions.TemplateNotFound: pysehtml_reportingtemplatesreport2.jinja2

### ISSUE THREAD

**Issue by nihaibao** [SeldomQA/seldom#1]
按照文档运行demo有这个问题
OSX，Python2.7

**Comment by defnngj** [comment]
应该是没有安装 nose-html-reporting ，或卸载重新安装。
通过pip 安装：> pip install nose-html-reporting

**Comment by nihaibao** [comment]
卸了重装还是这个错误。运行的是pyse里面的demo。

Traceback (most recent call last):
  File "/usr/local/bin/nosetests", line 9, in <module>
    load_entry_point('nose==1.3.7', 'console_scripts', 'nosetests')()
  File "/Library/Python/2.7/site-packages/nose-1.3.7-py2.7.egg/nose/core.py", line 121, in __init__
    **extra_args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/main.py", line 95, in __init__
    self.runTests()
  File "/Library/Python/2.7/site-packages/nose-1.3.7-py2.7.egg/nose/core.py", line 207, in runTests
    result = self.testRunner.run(self.test)
  File "/Library/Python/2.7/site-packages/nose-1.3.7-py2.7.egg/nose/core.py", line 66, in run
    result.printErrors()
  File "/Library/Python/2.7/site-packages/nose-1.3.7-py2.7.egg/nose/result.py", line 110, in printErrors
    self.config.plugins.report(self.stream)
  File "/Library/Python/2.7/site-packages/nose-1.3.7-py2.7.egg/nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "/Library/Python/2.7/site-packages/nose-1.3.7-py2.7.egg/nose/plugins/manager.py", line 167, in simple
    result = meth(*arg, **kw)
  File "/Library/Python/2.7/site-packages/nose_html_reporting/__init__.py", line 222, in report
    self.report_file.write(self.jinja.get_template(os.path.basename(self.report_template_filename)).render(
  File "/Library/Python/2.7/site-packages/Jinja2-2.8-py2.7.egg/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Library/Python/2.7/site-packages/Jinja2-2.8-py2.7.egg/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/Library/Python/2.7/site-packages/Jinja2-2.8-py2.7.egg/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: pysehtml_reportingtemplatesreport2.jinja2

**Comment by defnngj** [comment]
从报错上来是nose 和 nose_html_reporting引起的。请确认这两个库在 OSX 是否可用。别外，我没有在OSX 运行过pyse ， pyse中的路径用的“\\” 不知道是否支持 OSX 。 我只在windows下面开发pyse ，非windows平台未做验证。

**Comment by defnngj** [comment]
你好，该问题已经解决，请重新拉取一下该项目的最新代码。我在ubuntu下同要样发生了和你一样的问题，在ubuntu下已经修复，我想在OSX 也应该没问题了。
