### ISSUE TITLE
测试用例中执行两个用例，只有一个用例执行成功

### ISSUE THREAD

**Issue by tzk1986** [SeldomQA/seldom#111]
搭建了一个django的后台，用来测试登录，创建测试项目
使用seldom进行测试，测试登录，增删改查测试项目。
```python
import seldom


class TestPlatform(seldom.TestCase):
    def start(self):
        self.open(url="http://127.0.0.1:8000/admin/login/?next=/admin/")
        self.type(xpath='//*[@id="id_username"]', text="admin")
        self.type(xpath='//*[@id="id_password"]', text="admin")
        self.click(xpath='//*[@id="login-form"]/div[3]/input')
        # self.s = self.Session()
        print("一条测试用例开始")

    def end(self):
        self.quit()
        print("一条测试用例结束")

    def test_login(self):
        self.delete_all_cookies()
        self.refresh()
        self.wait(3)
        self.open(url="http://127.0.0.1:8000/admin/login/?next=/admin/")
        self.type(xpath='//*[@id="id_username"]', text="admin")
        self.type(xpath='//*[@id="id_password"]', text="admin")
        self.click(xpath='//*[@id="login-form"]/div[3]/input')

    def test_Project(self):
        self.open(url="http://127.0.0.1:8000/admin/project/project/add/")
        self.type(xpath='//*[@id="id_project_name"]', text="测试第一版")
        self.select(xpath='//*[@id="id_project_type"]', index=2)
        self.type(xpath='//*[@id="id_project_version"]', text="第一版")
        self.click(xpath='//*[@id="project_form"]/div/div/input[1]')
        self.wait(3)
        # 搜索
        self.click(xpath='//*[@id="changelist-filter"]/ul/li[1]/a')
        self.type(xpath='//*[@id="searchbar"]', text="测试第一版")
        self.click(xpath='//*[@id="changelist-search"]/div/input[2]')
        # 修改
        self.clear(xpath='//*[@id="id_form-0-project_version"]')
        self.type(xpath='//*[@id="id_form-0-project_version"]', text="第二版")
        self.click(xpath='//*[@id="changelist-form"]/p/input')
        # 删除
        self.click(xpath='//*[@id="result_list"]/tbody/tr[1]/td[1]/input')
        self.select(xpath='//*[@id="changelist-form"]/div[2]/label/select', value='delete_selected')
        self.click(xpath='//*[@id="changelist-form"]/div[2]/button')
        self.wait(5)
        self.click(xpath='//*[@id="content"]/form/div/input[4]')
        self.screenshots(file_path='./reports')
        self.wait(5)

    def test_P(self):
        self.open(url="http://127.0.0.1:8000/admin/project/port/add/")
        self.assertInTitle("port")


if __name__ == '__main__':
    seldom.main(debug=True)
```
单独执行，都能成功，放在一起执行，就会报错，
```
Error
Traceback (most recent call last):
  File "/Users/tangzhongkai/PycharmProjects/2022unittest/venv/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/Users/tangzhongkai/PycharmProjects/2022unittest/venv/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/Users/tangzhongkai/PycharmProjects/2022unittest/venv/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tangzhongkai/PycharmProjects/2022unittest/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/tangzhongkai/PycharmProjects/2022unittest/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/tangzhongkai/PycharmProjects/2022unittest/venv/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1008, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 948, in send
    self.connect()
  File "/Users/tangzhongkai/PycharmProjects/2022unittest/venv/lib/python3.9/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/Users/tangzhongkai/PycharmProjects/2022unittest/venv/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x10f6b07c0>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tangzhongkai/PycharmProjects/seldomtest/mytest02/test_dir/test_seldom_pure.py", line 13, in start
    self.open(url="http://127.0.0.1:8000/admin/login/?next=/admin/")
  File "/Users/tangzhongkai/PycharmProjects/2022unittest/venv/lib/python3.9/site-packages/seldom/webdriver.py", line 231, in open
    self.visit(url)
  File "/Users/tangzhongkai/PycharmProjects/2022unittest/venv/lib/python3.9/site-packages/seldom/webdriver.py", line 222, in visit
    Seldom.driver.get(url)
  File "/Users/tangzhongkai/PycharmProjects/2022unittest/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 437, in get
    self.execute(Command.GET, {'url': url})
  File "/Users/tangzhongkai/PycharmProjects/2022unittest/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 423, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/Users/tangzhongkai/PycharmProjects/2022unittest/venv/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 333, in execute
    return self._request(command_info[0], url, body=data)
  File "/Users/tangzhongkai/PycharmProjects/2022unittest/venv/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 355, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/Users/tangzhongkai/PycharmProjects/2022unittest/venv/lib/python3.9/site-packages/urllib3/request.py", line 78, in request
    return self.request_encode_body(
  File "/Users/tangzhongkai/PycharmProjects/2022unittest/venv/lib/python3.9/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/Users/tangzhongkai/PycharmProjects/2022unittest/venv/lib/python3.9/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/tangzhongkai/PycharmProjects/2022unittest/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 813, in urlopen
    return self.urlopen(
  File "/Users/tangzhongkai/PycharmProjects/2022unittest/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 813, in urlopen
    return self.urlopen(
  File "/Users/tangzhongkai/PycharmProjects/2022unittest/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 813, in urlopen
    return self.urlopen(
  File "/Users/tangzhongkai/PycharmProjects/2022unittest/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/Users/tangzhongkai/PycharmProjects/2022unittest/venv/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=52862): Max retries exceeded with url: /session/24f43cc23dd19ddbed64f8f88156bf07/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10f6b07c0>: Failed to establish a new connection: [Errno 61] Connection refused'))
```
后来，单独添加了一个打开的页面用例test_P，单独执行没有问题，两两组合执行还是不行

**Comment by defnngj** [comment]
```python
    def end(self):
        self.quit()
```

你不需要关心浏览器的关闭，seldom 所有用例运行完成会自动关闭将浏览。`end()` 方法在每条用例运行完成关闭。所以，第二条用例会失败。
