### ISSUE TITLE
在start中添加登录模块后，再在测试用例中打开其他页面，一个用例的话没有问题，两个用例的话，就有一个用例中的open是不执行的

### ISSUE THREAD

**Issue by tzk1986** [SeldomQA/seldom#113]
https://github.com/SeldomQA/seldom/issues/111，与之前的问题相关，解决了一个错误后，后续发现的问题，希望能帮忙解答下
@defnngj 还想问下，用例执行顺序的问题，查看代码的话，可以看到是三个用例，test_login，test_Project，test_P，的顺序，看执行过程的话，都是先执行最后一个用例test_P？

**Comment by tzk1986** [comment]
还是之前的django测试代码，这次报错，直接查看报告，可以确认为元素定位问题，从截图看，应该是第二次的open没有执行，还是在start登录后的页面中
```python
import seldom


class TestPlatform(seldom.TestCase):
    def start(self):
        self.open(url="http://127.0.0.1:8000/admin/login/?next=/admin/")
        self.type(xpath='//*[@id="id_username"]', text="admin")
        self.type(xpath='//*[@id="id_password"]', text="admin")
        self.click(xpath='//*[@id="login-form"]/div[3]/input')
        # self.s = self.Session()
        print("一条测试用例开始")

    def end(self):

        print("一条测试用例结束")

    def test_login(self):
        self.delete_all_cookies()
        self.refresh()
        self.wait(3)
        self.open(url="http://127.0.0.1:8000/admin/login/?next=/admin/")
        self.type(xpath='//*[@id="id_username"]', text="admin")
        self.type(xpath='//*[@id="id_password"]', text="admin")
        self.click(xpath='//*[@id="login-form"]/div[3]/input')

    def test_Project(self):
        self.open(url="http://127.0.0.1:8000/admin/project/project/add/")
        self.type(xpath='//*[@id="id_project_name"]', text="测试第一版")
        self.select(xpath='//*[@id="id_project_type"]', index=2)
        self.type(xpath='//*[@id="id_project_version"]', text="第一版")
        self.click(xpath='//*[@id="project_form"]/div/div/input[1]')
        self.wait(3)
        # 搜索
        self.click(xpath='//*[@id="changelist-filter"]/ul/li[1]/a')
        self.type(xpath='//*[@id="searchbar"]', text="测试第一版")
        self.click(xpath='//*[@id="changelist-search"]/div/input[2]')
        # 修改
        self.clear(xpath='//*[@id="id_form-0-project_version"]')
        self.type(xpath='//*[@id="id_form-0-project_version"]', text="第二版")
        self.click(xpath='//*[@id="changelist-form"]/p/input')
        # 删除
        self.click(xpath='//*[@id="result_list"]/tbody/tr[1]/td[1]/input')
        self.select(xpath='//*[@id="changelist-form"]/div[2]/label/select', value='delete_selected')
        self.click(xpath='//*[@id="changelist-form"]/div[2]/button')
        self.wait(5)
        self.click(xpath='//*[@id="content"]/form/div/input[4]')
        self.screenshots(file_path='./reports')
        self.wait(5)

    def test_P(self):
        self.open(url="http://127.0.0.1:8000/admin/project/port/add/")
        self.assertInTitle("port")


if __name__ == '__main__':
    seldom.main(debug=False)
```
同样试过，两两组合去进行测试，发现是报同样的错误
```
et1.1.2: 2022-05-27 11:07:12 webdriver.py | INFO | 📖 http://127.0.0.1:8000/admin/login/?next=/admin/
Traceback (most recent call last):
  File "/Users/tangzhongkai/PycharmProjects/2022unittest/venv/lib/python3.9/site-packages/seldom/case.py", line 50, in setUp
    self.start()
  File "/Users/tangzhongkai/PycharmProjects/seldomtest/mytest02/test_dir/test_seldom_pure.py", line 14, in start
    self.type(xpath='//*[@id="id_username"]', text="admin")
  File "/Users/tangzhongkai/PycharmProjects/2022unittest/venv/lib/python3.9/site-packages/seldom/webdriver.py", line 263, in type
    elem = web_elem.get_elements(index)
  File "/Users/tangzhongkai/PycharmProjects/2022unittest/venv/lib/python3.9/site-packages/seldom/webdriver.py", line 98, in get_elements
    raise NotFindElementError(self.find_elem_warn)
seldom.logging.exceptions.NotFindElementError: Message: ❌ Find 0 element through: xpath=//*[@id="id_username"]
```
以下是对应的截图，可以看出并没有跳转到相应的open中设置的链接，所以找不到定位元素
![image](https://user-images.githubusercontent.com/103291191/170621627-63580c04-f2c4-459a-a115-0c4e0061aedd.png)

**Comment by defnngj** [comment]
纯属业务逻辑问题：`start()` 会在每个用例开始之前执行。 你在 `test_login()` 执行登录，现在处于登录状态，然后第二条用例又会执行 `start()`  进行登录，肯定报错。

举个例子：
1. 开门 -> 退出房间 ->  开门 -> 进入房间。
2. 开门 -> 进入房间

1 和 2 单独执行都没问题。

合并到一起执行

开门 -> 退出房间 ->  开门 -> `进入房间 -> 开门` -> 进入房间


 `进入房间 -> 开门`  --> 已经在房间里了，怎么开门？

**Comment by tzk1986** [comment]
> 

意思我理解了，那我就把start去除了，执行，
但是执行后，还是会先执行test_P这个用例，导致没有登录页面，提示没有页面元素，这是怎么回事？
具体的测试用例执行顺序是怎么判断的?

**Comment by defnngj** [comment]
用例步骤设计不合理导致。
