### ISSUE TITLE
【bug】 seldom-platform平台针对多个项目同步用例引起错误

### ISSUE THREAD

**Issue by defnngj** [SeldomQA/seldom#158]
关联seldom-platform平台问题：

https://github.com/SeldomQA/seldom-platform/issues/11

```shell
Path must be within the project
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/ninja/operation.py", line 99, in run
    result = self.view_func(request, **values)
  File "/Users/zhiheng.hu/klpro/github/seldom-platform/backend/app_project/api.py", line 173, in sync_project_case
    main_extend = TestMainExtend(path=test_dir)
  File "/usr/local/lib/python3.9/site-packages/seldom/running/runner.py", line 248, in __init__
    super().__init__(path=path, browser=browser, base_url=base_url, debug=debug, timeout=timeout,
  File "/usr/local/lib/python3.9/site-packages/seldom/running/runner.py", line 150, in __init__
    self.TestSuits = seldomTestLoader.discover(self.path)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/loader.py", line 349, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/loader.py", line 387, in _find_tests
    name = self._get_name_from_path(start_dir)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/loader.py", line 371, in _get_name_from_path
    assert not _relpath.startswith('..'), "Path must be within the project"
AssertionError: Path must be within the project
Internal Server Error: /api/project/1/sync_case
```

**Comment by defnngj** [comment]
实现 `rediscover()` 方法（移除`self._top_level_dir`），替换`discover()` 方法。 从而解决上面的问题。

**Comment by defnngj** [comment]
问题已解决，关闭！
