### ISSUE TITLE
【bug】 diff_json 对比方法错误

### ISSUE THREAD

**Issue by defnngj** [SeldomQA/seldom#197]
* 问题：

```python
a = {"error":{"code":"","message":""},"result":{"booking_list":[{}],"Total":1},"success": True}
b = {"error":{"code":"","message":""},"result":{"booking_list":[{}],"Total":1},"success":True}

from seldom.utils import diff_json
diff_json(a, b)
```

* 报错

```shell
/Users/zhiheng.hu/klpro/gitlab/klook_autoapitest/t_sample.py
Traceback (most recent call last):
  File "/Users/zhiheng.hu/klpro/gitlab/klook_autoapitest/t_sample.py", line 27, in <module>
    diff_json(a, b)
  File "/Users/zhiheng.hu/.local/share/virtualenvs/klook_autoapitest-4W43aEPJ/lib/python3.9/site-packages/seldom/utils/diff.py", line 34, in diff_json
    diff_json(response_data[key], assert_data[key], exclude)
  File "/Users/zhiheng.hu/.local/share/virtualenvs/klook_autoapitest-4W43aEPJ/lib/python3.9/site-packages/seldom/utils/diff.py", line 34, in diff_json
    diff_json(response_data[key], assert_data[key], exclude)
  File "/Users/zhiheng.hu/.local/share/virtualenvs/klook_autoapitest-4W43aEPJ/lib/python3.9/site-packages/seldom/utils/diff.py", line 44, in diff_json
    response_data = sorted(response_data, key=lambda x: x[list(response_data[0].keys())[0]])
  File "/Users/zhiheng.hu/.local/share/virtualenvs/klook_autoapitest-4W43aEPJ/lib/python3.9/site-packages/seldom/utils/diff.py", line 44, in <lambda>
    response_data = sorted(response_data, key=lambda x: x[list(response_data[0].keys())[0]])
IndexError: list index out of range
```

**Comment by defnngj** [comment]
`seldom 3.3.0` 解决
