### ISSUE TITLE
使用assertText断言报错，提示driver找不到

### ISSUE THREAD

**Issue by Slee-Li** [SeldomQA/seldom#25]
使用assertText断言报错，提示driver找不到
et1.1.2: Traceback (most recent call last):
  File "/Users/sleeli/Desktop/programfile/PycharmProjects/testBSC/CRC2.3/test_dir/test_login.py", line 43, in test_login_case
    self.assertText("lizhen")
  File "/Users/sleeli/.pyenv/versions/3.7.4/lib/python3.7/site-packages/seldom/case.py", line 102, in assertText
    elem = self.driver.find_element_by_tag_name("html")
AttributeError: 'LoginPageTest' object has no attribute 'driver'

**Comment by Slee-Li** [comment]
看了下代码seldom/case.py的102行，应该你是吧Seldom写错成self导致的，如下修改后正常
将102的
elem = self.driver.find_element_by_tag_name("html")
修改为
elem = Seldom.driver.find_element_by_tag_name("html")
然后就可以了，希望虫师有时间能修改下

**Comment by Slee-Li** [comment]
但是我再次使用有遇到了新问题，在is_displayed报错了，但是我其他的一个断言成功了，感觉跟页面元素有关系
et1.1.2: Traceback (most recent call last):
  File "/Users/sleeli/Desktop/programfile/PycharmProjects/testBSC/CRC2.3/test_dir/test_login.py", line 44, in test_login_case
    self.assertText("lizhen")
  File "/Users/sleeli/.pyenv/versions/3.7.4/lib/python3.7/site-packages/seldom/case.py", line 105, in assertText
    if elem.is_displayed():
  File "/Users/sleeli/.pyenv/versions/3.7.4/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 488, in is_displayed
    self)
  File "/Users/sleeli/.pyenv/versions/3.7.4/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/Users/sleeli/.pyenv/versions/3.7.4/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/sleeli/.pyenv/versions/3.7.4/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=81.0.4044.138)

**Comment by klookAppTest** [comment]
该问题已经修复， 安装：
```
python3 -m pip install seldom==1.5.2 
```
