### ISSUE TITLE
运行接口测试报错~！

### ISSUE THREAD

**Issue by defnngj** [SeldomQA/seldom#68]
```
 python .\run.py
2021-06-30 22:16:04 [INFO]
              __    __
   ________  / /___/ /___  ____ ____
  / ___/ _ \/ / __  / __ \/ __ ` ___/
 (__  )  __/ / /_/ / /_/ / / / / / /
/____/\___/_/\__,_/\____/_/ /_/ /_/
-----------------------------------------
                             @itest.info

Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\run.py", line 9, in <module>
    seldom.main(path="./test_dir/",
  File "C:\Python38\lib\site-packages\seldom-2.1.1-py3.8.egg\seldom\running\next_runner.py", line 96, in __init__
    self._run_test_case(suits)
  File "C:\Python38\lib\site-packages\seldom-2.1.1-py3.8.egg\seldom\running\next_runner.py", line 127, in _run_test_case
    runner.run(suits, rerun=self.rerun, save_last_run=self.save_last_run)
  File "C:\Python38\lib\site-packages\seldom-2.1.1-py3.8.egg\seldom\running\HTMLTestRunner.py", line 319, in run
    test(result)
  File "C:\Python38\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Python38\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Python38\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Python38\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Python38\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Python38\lib\unittest\suite.py", line 122, in run
  File "C:\Python38\lib\unittest\case.py", line 736, in __call__
    return self.run(*args, **kwds)
  File "C:\Python38\lib\unittest\case.py", line 684, in run
  File "C:\Python38\lib\unittest\case.py", line 602, in _feedErrorsToResult
    result.addError(test, exc_info)
  File "C:\Python38\lib\site-packages\seldom-2.1.1-py3.8.egg\seldom\running\HTMLTestRunner.py", line 252, in addError
    if type(getattr(test, "driver", "")).__name__ == 'WebDriver':
  File "C:\Python38\lib\site-packages\seldom-2.1.1-py3.8.egg\seldom\case.py", line 64, in driver
    Seldom.driver = Chrome()
  File "C:\Python38\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Python38\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
```

**Comment by defnngj** [comment]
fix: version 2.2.1

**Comment by defnngj** [comment]
已修复
